### PR TITLE
Update to phergie/phergie-irc-plugin-react-url version 3

### PR DESCRIPTION
**Pull request by sitedyno**

### CODE REVIEW

**Comment by elazar** [comment]
@sitedyno This breaks tests. :cry:

**Comment by sitedyno** [comment]
When have tests worked on this plugin? ;)

**Comment by sitedyno** [comment]
Ok I'll make the tests happy, but for the record the tests haven't worked before so far as Travis shows:
https://travis-ci.org/phergie/phergie-irc-plugin-react-twitter/builds

I did not break them.

**Comment by elazar** [comment]
@sitedyno Point taken. Thanks for fixing that up. :smile:

**Pull request merged**
